name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/binary-cache/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/.cargo/script-cache/
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          ~/.cargo/.package-cache
          ~/.cargo/.rustc_info.json
          target/
        key: Cargo-${{ runner.os }}
    - name: Check
      run: cargo check --all-targets --all-features
    - name: Fmt
      run:  cargo fmt -- --check || cargo fmt
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test
    - name: Publish (DryRun)
      run: cargo publish --manifest-path assert_fn/Cargo.toml --dry-run
    - name: Bump Version
      run: |
        cargo install cargo-script cargo-workspaces
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'danrspen@gmail.com'
        cargo script bin/bump_versions.rs
